# Generated by Django 4.2.30 on 2026-07-18 04:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0005_alter_investment_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('topup', 'Top-up'), ('purchase', 'Purchase'), ('withdrawal', 'Withdrawal'), ('refund', 'Refund'), ('fee', 'Fee')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('merchant_name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('reference_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='completed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='investments.virtualcard')),
            ],
            options={
                'verbose_name': 'Card Transaction',
                'verbose_name_plural': 'Card Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['card', 'created_at'], name='investments_card_id_1e4f80_idx'), models.Index(fields=['reference_id'], name='investments_referen_dff3bb_idx')],
            },
        ),
    ]
