# Generated by Django 4.2.30 on 2026-07-18 04:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_on_deposit', models.BooleanField(default=True, help_text='Email when deposit is approved')),
                ('email_on_withdrawal', models.BooleanField(default=True, help_text='Email when withdrawal is processed')),
                ('email_on_investment', models.BooleanField(default=True, help_text='Email when investment is created')),
                ('email_on_profit', models.BooleanField(default=True, help_text='Email on profit credited')),
                ('email_on_kyc', models.BooleanField(default=True, help_text='Email on KYC status change')),
                ('email_on_referral', models.BooleanField(default=True, help_text='Email when someone uses your referral')),
                ('email_on_security', models.BooleanField(default=True, help_text='Email on security alerts')),
                ('push_enabled', models.BooleanField(default=False, help_text='Enable browser push notifications')),
                ('push_on_deposit', models.BooleanField(default=True)),
                ('push_on_withdrawal', models.BooleanField(default=True)),
                ('push_on_investment', models.BooleanField(default=True)),
                ('push_on_profit', models.BooleanField(default=False)),
                ('push_on_kyc', models.BooleanField(default=True)),
                ('push_on_referral', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False, help_text='Enable SMS notifications')),
                ('sms_on_deposit', models.BooleanField(default=False)),
                ('sms_on_withdrawal', models.BooleanField(default=True)),
                ('sms_on_security', models.BooleanField(default=True)),
                ('sound_enabled', models.BooleanField(default=True, help_text='Play sound for notifications')),
                ('daily_digest', models.BooleanField(default=False, help_text='Send daily summary email')),
                ('weekly_digest', models.BooleanField(default=False, help_text='Send weekly summary email')),
                ('marketing_emails', models.BooleanField(default=True, help_text='Receive promotional emails')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
    ]
